dist: trusty
language: cpp
compiler: gcc-5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
env:
  - ARCH=amd64
  - ARCH=i386
  - ARCH=arm
  - ARCH=arm64
  - ARCH=mips
  - ARCH=mips64
#  - ARCH=ppc
#  - ARCH=ppc64
matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      env:
        - ARCH=amd64
install:
  - git submodule init
  - git submodule update
  - ./.travis/installer.sh
  - ls -la /usr/bin | grep gcc
  - ls -la /usr/bin | grep g++
script:
  - echo "${ARCH}"
  - sh build -j2 ${ARCH}
  - ./.travis/test.sh
  # - ./.travis/release.sh
