environment:
  matrix:
    - image: Visual Studio 2015

platform:
  - x86
  - x64

install:
  - git submodule init
  - git submodule update

test_script:
  - IF /I "%PLATFORM%" == "x64" ECHO "x64 building..." && CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64 &&   build release amd64 && cd test && ..\bin\Windows_amd64_release\fibjs.exe main.js
  - IF /I "%PLATFORM%" == "x86" ECHO "x86 building..." && CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 &&   build release i386 && cd test && ..\bin\Windows_i386_release\fibjs.exe main.js

matrix:
  fast_finish: true

build: off